//! `vhd_bridge::secret` — embed the build-time `[u8; 32]` shared secret
//! and expose a minimum-scope accessor used only by HMAC computation.
//!
//! The 32-byte `RustDeskClientSharedSecret` is `include!()`-embedded
//! from the OUT_DIR file generated by `build.rs` (task 1.2). It is read
//! only from inside [`with_shared_secret`] so that no other code path
//! can name it directly. Per Requirement 3.7 / 3.8 / 3.11 the secret
//! bytes never appear in `BridgeConfig`, IPC messages, logs, Debug
//! impls, or panics — only [`SHARED_SECRET_VERSION`] is observable.
//!
//! The whole submodule is feature-gated by its parent (`mod.rs` declares
//! `mod secret;` under `#[cfg(all(target_os = "windows", feature =
//! "vhd-bridge"))]`), so no extra `cfg` attribute is needed here.

#![allow(dead_code)] // populated by hmac.rs in task 4.2; module is gated by parent.

/// 32-byte shared secret, embedded at compile time from
/// `${OUT_DIR}/vhd_bridge_secret.rs` (written by `build.rs`).
///
/// The constant is `pub(super)` so HMAC builders inside this crate can
/// reference it via [`with_shared_secret`]; nothing outside the
/// `vhd_bridge` module tree can name it. Do **not** add `Debug`,
/// `Display`, or any logging path that prints this value.
pub(super) const SHARED_SECRET: [u8; 32] =
    include!(concat!(env!("OUT_DIR"), "/vhd_bridge_secret.rs"));

/// Compile-time secret version number, embedded from
/// `${OUT_DIR}/vhd_bridge_secret_version.rs`. Unlike [`SHARED_SECRET`],
/// this value is safe to expose in IPC observability and `--version`
/// output (Requirement 3.7 / 3.11 / 14.4).
pub(super) const SHARED_SECRET_VERSION: u32 =
    include!(concat!(env!("OUT_DIR"), "/vhd_bridge_secret_version.rs"));

/// Borrow the 32-byte shared secret for the duration of `f`, then drop
/// the borrow.
///
/// This is the **only** sanctioned way to read the secret bytes; HMAC
/// builders in `hmac.rs` MUST go through this function. Any other call
/// site naming `SHARED_SECRET` directly is a bug because it bypasses
/// the single audit point and risks accidental leakage into logs,
/// `Debug` impls, or panic messages.
#[inline]
pub(super) fn with_shared_secret<R>(f: impl FnOnce(&[u8; 32]) -> R) -> R {
    f(&SHARED_SECRET)
}
